In [1]:
import numpy as np
import pandas as pd
import scipy

import pickle

import nltk
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [2]:
with open('../prep_tweets.pickle', 'rb') as f:
    df = pickle.load(f)
    
df.head(5)

,id,label,tweet,cleen_tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,@user when a father is dysfunctional and is s...,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc...","[father, dysfunctional, selfish, drag, kid, dy..."
1,2,0.0,@user @user thanks for #lyft credit i can't us...,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc...","[thanks, lyft, credit, use, cause, offer, whee..."
2,3,0.0,bihday your majesty,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]","[bihday, majesty]"
3,4,0.0,#model i love u take with u all the time in ...,model love you take with you all the time in ur,"[model, love, you, take, with, you, all, the, ...","[model, love, take, time, ur]","[model, love, take, time, ur]","[model, love, take, time, ur]"
4,5,0.0,factsguide: society now #motivation,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]","[factsguid, societi, motiv]","[factsguide, society, motivation]"

In [3]:
df['tweet_token'] = df['tweet_token'].apply(lambda x: ' '.join(x))
df['tweet_token_filtered'] = df['tweet_token_filtered'].apply(lambda x: ' '.join(x))
df['tweet_stemmed'] = df['tweet_stemmed'].apply(lambda x: ' '.join(x))
df['tweet_lemmatized'] = df['tweet_lemmatized'].apply(lambda x: ' '.join(x))

df.head(5)

,id,label,tweet,cleen_tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,@user when a father is dysfunctional and is s...,when father is dysfunctional and is so selfish...,when father is dysfunctional and is so selfish...,father dysfunctional selfish drags kids dysfun...,father dysfunct selfish drag kid dysfunct run,father dysfunctional selfish drag kid dysfunct...
1,2,0.0,@user @user thanks for #lyft credit i can't us...,thanks for lyft credit cannot use cause they d...,thanks for lyft credit can not use cause they ...,thanks lyft credit use cause offer wheelchair ...,thank lyft credit use caus offer wheelchair va...,thanks lyft credit use cause offer wheelchair ...
2,3,0.0,bihday your majesty,bihday your majesty,bihday your majesty,bihday majesty,bihday majesti,bihday majesty
3,4,0.0,#model i love u take with u all the time in ...,model love you take with you all the time in ur,model love you take with you all the time in ur,model love take time ur,model love take time ur,model love take time ur
4,5,0.0,factsguide: society now #motivation,factsguide society now motivation,factsguide society now motivation,factsguide society motivation,factsguid societi motiv,factsguide society motivation

Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
* Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
* Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
* Исключим стоп-слова с помощью stop_words='english'. 
* Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().

In [4]:
stop_words = nltk.corpus.stopwords.words('english')

params = {
    'max_df': 0.9, 
    'max_features': 1000, 
    'stop_words': stop_words
}

In [5]:
count_vectorizer = CountVectorizer(**params)

stemmed_words = count_vectorizer.fit_transform(df['tweet_stemmed'])
stemmed_features = count_vectorizer.get_feature_names()

pd.DataFrame(stemmed_words.toarray(), columns=stemmed_features).head(5)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,year,yesterday,yet,yo,yoga,york,young,youtub,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
count_vectorizer = CountVectorizer(**params)

lemmatized_words = count_vectorizer.fit_transform(df['tweet_lemmatized'])
lemmatized_features = count_vectorizer.get_feature_names()

pd.DataFrame(lemmatized_words.toarray(), columns=lemmatized_features).head(5)

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yes,yesterday,yet,yo,yoga,york,young,youtube,yr,yummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
* Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
* Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
* Исключим стоп-слова с помощью stop_words='english'.
* Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().

In [7]:
tfidf_vectorizer = TfidfVectorizer(**params)

stemmed_words = tfidf_vectorizer.fit_transform(df['tweet_stemmed'])
stemmed_features = tfidf_vectorizer.get_feature_names()

pd.DataFrame(stemmed_words.toarray(), columns=stemmed_features).head(5)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,year,yesterday,yet,yo,yoga,york,young,youtub,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
tfidf_vectorizer = TfidfVectorizer(**params)

lemmatized_words = tfidf_vectorizer.fit_transform(df['tweet_lemmatized'])
lemmatized_features = tfidf_vectorizer.get_feature_names()

pd.DataFrame(lemmatized_words.toarray(), columns=lemmatized_features).head(5)

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yes,yesterday,yet,yo,yoga,york,young,youtube,yr,yummy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте таблицу метод векторизации и скор который вы получили (в методах векторизации по изменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы

In [9]:
df['label'].value_counts()

0.0    29720
1.0     2242
Name: label, dtype: int64

Классы несбалансированы, поэтому в качестве метрики будем использовать F-меру.

In [10]:
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve
from sklearn.pipeline import Pipeline

In [11]:
def get_score(data, labels, processings):
    
    X_train, X_test, y_train, y_test = train_test_split(data, 
                                                        labels, 
                                                        stratify=labels, 
                                                        test_size=0.2, 
                                                        random_state=42)
    
    for processing in processings:
        if isinstance(X_train, scipy.sparse.csr.csr_matrix):
            X_train = X_train.toarray()
            X_test = X_test.toarray()
        X_train = processing.fit_transform(X_train)
        X_test = processing.transform(X_test)
    
    model = LogisticRegression()
    model.fit(X_train, y_train)
    # вероятности первого класса
    preds = model.predict_proba(X_test)[:, 1]
    
    # берем максимальное значение f-меры
    precision, recall, thresholds = precision_recall_curve(y_test, preds)
    f1 = (2 * precision * recall) / (precision + recall + 1e-7)

    return round(np.max(f1), 4)


def get_results(data, labels, vectorizers, params, num_features, decompose=False): 
    index = []
    results = []

    for name, vectorizer in vectorizers.items():
        index.append(name)
        
        columns = []
        scores = []
        for num in num_features:
            params['max_features'] = num
            processings = [vectorizer(**params)]
            
            col_name = num
            
            if decompose:
                n_components = num//2
                pca = PCA(n_components=n_components)
                processings.append(pca)

                col_name = f'{num} --> {n_components}'
            
            scores.append(get_score(data, labels, processings))
            columns.append(col_name)
        
        results.append(scores)
        
    return pd.DataFrame(results, index=index, columns=columns)

In [12]:
data = df[df['label'].notnull()]['tweet_stemmed']
labels = df[df['label'].notnull()]['label']

num_features = [500, 1000, 2000, 3000]
vectorizers = {
    'count_vectorizer': CountVectorizer, 
    'tfidf_vectorizer': TfidfVectorizer
}

In [13]:
%%time
get_results(data, labels, vectorizers, params, num_features, decompose=False)

CPU times: user 3.77 s, sys: 1.89 ms, total: 3.78 s
Wall time: 3.78 s

                    500     1000    2000    3000
count_vectorizer  0.5448  0.5698  0.6304  0.6706
tfidf_vectorizer  0.5451  0.5932  0.6509  0.6704

Наблюдается рост метрики по мере увеличения количества признаков.

Применим PCA для сокращения размерности.

In [14]:
%%time
get_results(data, labels, vectorizers, params, num_features, decompose=True)

CPU times: user 17min 59s, sys: 4min 7s, total: 22min 7s
Wall time: 3min 5s

                  500 --> 250  1000 --> 500  2000 --> 1000  3000 --> 1500
count_vectorizer       0.5049        0.5576         0.6058         0.6377
tfidf_vectorizer       0.5169        0.5737         0.6124         0.6383

Применив PCA удалось вдвое сократить количество признаков, при этом не сильно теряя в качестве. Но SVD является довольно затратной операцией. Время выполнения функции увеличилось почти на два порядка.